### ISSUE TITLE
Consider client architecture review - so that client runs as standalone app.

### ISSUE THREAD

**Issue by stefek99** [aeternity/testnet#23] opened 2017-04-09 11:13 UTC
Currently to run the website: Erlang and all dependencies required.

It can be intimidating to someone.

We should make it super easy for designers, usability experts, front-end developers to work on the website.

Clone repo and done.

🙏

**Comment by stephenmoloney** [comment] 2017-04-09 11:38
Would it be possible to use [mix](https://hexdocs.pm/mix/Mix.html) to 
build and run an `erlang` project? I haven't really looked into it.

mix is an easy tool to use.

**Comment by weaktyper** [comment] 2017-04-09 11:40
Would it be possible to use [mix](https://hexdocs.pm/mix/Mix.html) to 
build and run an `erlang` project? I haven't really looked into it.

mix is an easy tool to use.

**Comment by stefek99** [comment] 2017-04-09 12:34
Maybe / not sure / not an expert.

In principle - make it easy to contribute.

I provided instructions how to run on Mac: https://github.com/aeternity/testnet/issues/18

Can spend some time to get it sorted on Windows.

It's about not installing anything at all but get it up and running on any machine in a matter of seconds.

Think about all the design / usability folks who are not familiar with command line.

**Comment by Leonyxtested** [comment] 2017-04-09 12:39
En Windows 10 estoy intentando que alguien lo pruebe,el terminal es en Linux por lo que podria usarse,en otros Windows no sabria.

En mi fork estoy intendo traducir los comentarios en el codigo e incluir comentarios de que significa y como funciona,pero en Español,para los que no son expertos.

**Comment by weaktyper** [comment] 2017-04-09 14:40
@stefek99 
I don't think there is anyway to avoid asking users to install `erlang` on their machine themselves - other than perhaps a `dockerfile` and `docker-compose.yml` file. Installing erlang is not that hard really.

If user friendliness is the goal for *all* developers, I would suggest creating a mix umbrella app with a *at least* two separate apps:

1. `apps/telnet`
2. `apps/telnet_web` --> separate for all the web related stuff.

I think subdivision into other apps can be done later if you wanted.

Then let mix do the build.

I'm trying to create a simple demo of it but right now `HIPE` if causing my compilation to fail.

**Comment by zack-bitcoin** [comment] 2017-04-09 15:04
One goal is to make a javascript light wallet.
 It will download and verify all the headers.
So using aeternity will be as easy as visiting a website, no erlang necessary.
 Hopefully easier than a typical online banking experience.

Only miners, and nodes that keep track of the state tree need to use the erlang code.

**Comment by zack-bitcoin** [comment] 2017-04-11 09:29
This issue is a duplicate of #10

**Closed by zack-bitcoin** 2017-04-11 09:29 UTC
